---
- hosts: all
  tasks:
   - name: "include OpenConext-deploy vars"
     include_vars: "../../OpenConext-deploy/environments/vm/group_vars/vm.yml"
   - name: "Include OpenConext-deploy secrets"
     include_vars: "../../OpenConext-deploy/environments/vm/secrets/vm.yml"
   - name: "Include extra vars to override the vm vars"
     include_vars: "group_vars/override.yml"
   - name: "Include OpenConext-deploy all group vars"
     include_vars: "../../OpenConext-deploy/group_vars/all.yml"
   - name: "Include OpenConext-deploy java vars"
     include_vars: "../../OpenConext-deploy/group_vars/java-apps-common.yml"
   - name: Set base_domain  
     set_fact: 
       base_domain: dev.support.surfconext.nl
       engine_feature_ldap_integration: 0
  tags: always

- hosts: all
  become: true
  vars:
    spdashboard_document_root: /vagrant/web
    front_controller: app_dev.php
    spdashboard_domain: spdashboard.dev.support.surfconext.nl
    spdashboard_data_dir: /vagrant
    spdashboard_fpm_user: vagrant
  roles:
    - { role:  ../OpenConext-deploy/roles/common,                      tags: ['common'] }
    - { role:  ../OpenConext-deploy/roles/openconext-common,           tags: ['common'] }
    - { role: tls,                                                     tags: ['tls'] }
    - { role:  ../OpenConext-deploy/roles/httpd,                       tags: ['httpd'] }
    - { role: ../OpenConext-deploy/roles/php,                          tags: ['php'] }
    - { role: ../OpenConext-deploy/roles/mysql,                        tags: ['mysql'] }
    - { role: ../OpenConext-deploy/roles/engineblock,                  tags: ['eb'] }
    - { role: ../OpenConext-deploy/roles/java,                         tags: ['java' ] }
    - { role: ../OpenConext-deploy/roles/spdashboard,                  tags: ['spdashboard'] } 
    - { role: ../OpenConext-deploy/roles/mujina-idp,                   tags: ['legacy' ] }
    - { role: ../OpenConext-deploy/roles/mujina-sp,                    tags: ['legacy' ] }
    - { role: ../OpenConext-deploy/roles/shibboleth,                   tags: ['shib' ] }
    - { role: ../OpenConext-deploy/roles/mongo,                        tags: ['mongo'] }
    - { role: ../OpenConext-deploy/roles/manage-gui,                   tags: ['manage', 'manage-gui'] }
    - { role: ../OpenConext-deploy/roles/manage-server,                tags: ['manage', 'manage-server'] }
    - { role: manage-gui-prod,                                         tags: ['manage', 'manage-gui'] }
    - { role: manage-server-prod,                                      tags: ['manage', 'manage-server'] }
    - { role: ../OpenConext-deploy/roles/authz-server,                 tags: ['oauth', 'authz' ] }
    - { role: ../OpenConext-deploy/roles/authz-admin,                  tags: ['oauth', 'authz-admin' ] }
    - { role: ../OpenConext-deploy/roles/voot,                         tags: ['oauth', 'voot' ] }
    - { role: ../OpenConext-deploy/roles/teams-gui,                    tags: ['teams', 'teams-gui'  ] }
    - { role: ../OpenConext-deploy/roles/teams-server,                 tags: ['teams', 'teams-server'  ] }
    - { role: ../OpenConext-deploy/roles/attribute-aggregation-gui,    tags: ['attribute-aggregation', 'attribute-aggregation-gui'] }
    - { role: ../OpenConext-deploy/roles/attribute-aggregation-server, tags: ['attribute-aggregation', 'attribute-aggregation-server'] }
    - { role: ../OpenConext-deploy/roles/tomcat,                       tags: ['tomcat'] }
    - { role: ../OpenConext-deploy/roles/oidc,                         tags: ['oidc'] }
    - { role: ../OpenConext-deploy/roles/vm_only_provision_manage_eb,  tags: ['vm_only_provision_manage_eb'] }


- hosts: all
  become: true
  roles:
    - { role: ../OpenConext-deploy/roles/vm_only_provision_manage_eb,  tags: ['vm_only_provision_manage_eb'] }

